version: "3.8"

services:
  backend:
    restart: always
    container_name: back
    environment:
      BUILDKIT_INLINE_CACHE: 1
    image: cs320track2/backend
    build:  
      context: ./moral_kombat_backend/
      dockerfile: Dockerfile
    cache_from: 
      - cs320track2/backend:latest
    ports:
      - "8000:8000"
    networks:
      - default-net
    image: cs320track2/backend:latest
    depends_on: 
      - "database"
    command: ["./wait-for-it.sh", "db:5432", "--", "./start.sh"]
      
  database:
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: "password"
      BUILDKIT_INLINE_CACHE: 1
    build:
      context: ./database/
      dockerfile: Dockerfile
    cache_from: 
      - cs320track2/database:latest
    image: cs320track2/database:latest
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres.conf:/etc/postgresql/postgresql.conf
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - default-net

  frontend:
    restart: always
    command : npm start
    container_name: front
    environment:
      BUILDKIT_INLINE_CACHE: 1
    cache_from: 
      - cs320track2/frontend:latest
    image: cs320track2/frontend
    build:
      context: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - default-net
    image: cs320track2/frontend:latest

  apache:

    
networks:
  default-net:
    driver: bridge

volumes:
  postgres_data:
