version: "3.8"

services:
  backend:
    restart: always
    container_name: back
    environment:
      BUILDKIT_INLINE_CACHE: 1
    image: cs320track2/backend
    build:
      context: ./moral_kombat_backend/
      dockerfile: Dockerfile
      cache_from:
        - cs320track2/backend:latest
    command: bash -c "cd lead && python manage.py check --tag database && python manage.py runserver 0.0.0.0:8000"
    networks:
      - default-net
    image: cs320track2/backend:latest
    depends_on:
      - "database"

  database:
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: "password"
      BUILDKIT_INLINE_CACHE: 1
    build:
      context: ./database/
      dockerfile: Dockerfile
      cache_from:
        - cs320track2/database:latest
    image: cs320track2/database:latest
    volumes:
      - ./database/postgres.conf:/etc/postgresql/postgresql.conf
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - default-net

  frontend:
    restart: always
    command : npm start
    container_name: front
    environment:
      BUILDKIT_INLINE_CACHE: 1
      CI: "true"
    image: cs320track2/frontend
    build:
      context: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
      dockerfile: Dockerfile
      cache_from:
      - cs320track2/frontend:latest
    stdin_open: true
    depends_on:
      - backend
    networks:
      - default-net

networks:
  default-net:
    driver: bridge

volumes:
  postgres_data:
