version: "3.8"

services:
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./moral_kombat_backend:/app/api
    environment:
      CHOKIDAR_USEPOLLING: "true" 
    build:
      context: ./database/
      dockerfile: Dockerfile
      cache_from:
        - cs320track2/database:latest
  database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    build:
      context: ./database/
      dockerfile: Dockerfile
      cache_from:
        - cs320track2/database:latest
  frontend:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./Ghost_in_the_Shell/client_folder_react_app/ethisim:/app/frontend
      - /app/frontend/node_modules
    build:
      context: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
      dockerfile: Dockerfile
      cache_from:
      - cs320track2/frontend:latest
