version: "2.4"

services:

  apache:
    restart: always
    container_name: apache
    env_file: .env
    stdin_open: true
    networks:
      - default-net
    ports: 
      - "80:80"
      - "443:443"
      - "5000:5000"
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - httpd_log:/var/log/httpd
      - shibd_log:/var/log/shibd
    command: bash -c "chmod +x /etc/shibboleth/shib_start.sh && /etc/shibboleth/shib_start.sh"

networks:
  default-net:
    driver: bridge


volumes:
  httpd_log:
  shibd_log:

