version: "3.8"

services:
  backend:
    restart: always
    command: bash -c "cd lead && python manage.py runserver 0.0.0.0:8000"
    container_name: back
    build:  
      context: ./moral_kombat_backend/
      dockerfile: Dockerfile
    volumes: 
      - .:/app/code/
    ports:
      - "8000:8000"
    networks:
      - default-net
    image: cs320track2/backend

  editor-frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - default-net
    image: cs320track2/frontend
networks:
  default-net:
    driver: bridge

volumes:
  postgres_data:
