version: "3.7"

services:
  backend:
    restart: always
    command: bash -c "cd lead && python manage.py runserver 0.0.0.0:8000"
    image: judgerussell/track2backend
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command : npm start
    image: judgerussell/track2frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

volumes:
  postgres_data: