# Generated by Django 3.1.7 on 2021-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210506_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
