# Generated by Django 2.2.12 on 2021-04-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210408_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generic_page',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='reflection_questions',
            old_name='id',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='VERSION',
        ),
        migrations.AddField(
            model_name='action_page',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action_page',
            name='VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='action_page2', to='tables.PAGES', to_field='VERSION', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversations',
            name='STAKEHOLDER_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations2', to='tables.STAKEHOLDERS', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coverage',
            name='STAKEHOLDER_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coverage4', to='tables.STAKEHOLDERS', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='NEXT_PAGE_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages3', to='tables.PAGES', to_field='VERSION', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages_to_scenario',
            name='PAGE_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stakeholder_page1', serialize=False, to='tables.PAGES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages_to_scenario',
            name='PAGE_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page3', to='tables.PAGES', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages_to_scenario',
            name='SCENARIO_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page2', to='tables.SCENARIOS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_question_to_page',
            name='PAGE_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions_to_page1', to='tables.PAGES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_question_to_page',
            name='PAGE_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions_to_page4', to='tables.PAGES', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_question_to_page',
            name='REFLECTION_QUESTION_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions_to_page3', to='tables.REFLECTION_QUESTIONS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_question_to_page',
            name='REFLECTION_QUESTION_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_questions_to_page2', to='tables.REFLECTION_QUESTIONS', to_field='REFLECTION_QUESTION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response_to_action_page',
            name='ACTION_PAGE_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='action_page4', to='tables.ACTION_PAGE', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responses',
            name='PAGE_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses69', to='tables.PAGES', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responses_to_conversations',
            name='STAKEHOLDER_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsesTC69', to='tables.STAKEHOLDERS', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder_to_page',
            name='PAGE_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page7', to='tables.PAGES', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder_to_page',
            name='STAKEHOLDER_VERSION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page8', to='tables.STAKEHOLDERS', to_field='VERSION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholders',
            name='ENABLE_MULTI_CONVO',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action_page',
            name='PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_page1', to='tables.PAGES'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='STAKEHOLDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations1', to='tables.STAKEHOLDERS'),
        ),
        migrations.AlterField(
            model_name='courses_to_scenario',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reflections_taken1', serialize=False, to='tables.COURSES'),
        ),
        migrations.AlterField(
            model_name='courses_to_scenario',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections_taken2', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='ISSUE',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coverage1', to='tables.ISSUES'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='STAKEHOLDER',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coverage2', serialize=False, to='tables.STAKEHOLDERS'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='GRADE',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='tables.STUDENTS'),
        ),
        migrations.AlterField(
            model_name='generic_page',
            name='BODY',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='generic_page',
            name='PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_page1', to='tables.PAGES', unique=True),
        ),
        migrations.AlterField(
            model_name='generic_page',
            name='VERSION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_page2', to='tables.PAGES', to_field='VERSION', unique=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='SCENARIO_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_id1', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='NEXT_PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages2', to='tables.PAGES', unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages1', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='professors_to_courses',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_to_courses2', to='tables.COURSES'),
        ),
        migrations.AlterField(
            model_name='professors_to_courses',
            name='PROFESSOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professors_to_courses1', serialize=False, to='tables.PROFESSORS'),
        ),
        migrations.AlterField(
            model_name='professors_to_scenario',
            name='PROFESSOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professors_to_scenario1', serialize=False, to='tables.PROFESSORS'),
        ),
        migrations.AlterField(
            model_name='professors_to_scenario',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors_to_scenario2', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='RESPONSE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_had5', to='tables.RESPONSES'),
        ),
        migrations.AlterField(
            model_name='response_to_action_page',
            name='ACTION_PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_page3', to='tables.ACTION_PAGE'),
        ),
        migrations.AlterField(
            model_name='response_to_action_page',
            name='RESPONSE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_page2', to='tables.RESPONSES'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses4', to='tables.COURSES'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses3', to='tables.PAGES'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses2', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses1', to='tables.STUDENTS'),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='CONVERSATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsesTC3', to='tables.CONVERSATIONS'),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='RESPONSE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsesTC1', to='tables.RESPONSES'),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='STAKEHOLDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsesTC2', to='tables.STAKEHOLDERS'),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='PROFESSOR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_creator2', to='tables.PROFESSORS'),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='SCENARIO_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scenarios_for',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_for2', to='tables.COURSES'),
        ),
        migrations.AlterField(
            model_name='scenarios_for',
            name='SCENARIO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scenarios_for1', serialize=False, to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='stakeholder_to_page',
            name='PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page5', to='tables.PAGES'),
        ),
        migrations.AlterField(
            model_name='stakeholder_to_page',
            name='STAKEHOLDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page6', to='tables.STAKEHOLDERS'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='SCENARIO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders1', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='VERSION',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_times3', to='tables.COURSES'),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='SCENARIO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_times2', to='tables.SCENARIOS'),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_times1', to='tables.STUDENTS'),
        ),
        migrations.AlterField(
            model_name='students_to_course',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_to_couse2', to='tables.COURSES'),
        ),
        migrations.AlterField(
            model_name='students_to_course',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students_to_course1', serialize=False, to='tables.STUDENTS'),
        ),
        migrations.AlterUniqueTogether(
            name='action_page',
            unique_together={('PAGE', 'CHOICE', 'ID', 'RESULT_PAGE')},
        ),
        migrations.AlterUniqueTogether(
            name='generic_page',
            unique_together={('ID', 'VERSION')},
        ),
        migrations.AlterUniqueTogether(
            name='pages_to_scenario',
            unique_together={('PAGE_ID', 'SCENARIO_ID', 'PAGE_VERSION')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection_question_to_page',
            unique_together={('PAGE_ID', 'REFLECTION_QUESTION_VERSION', 'REFLECTION_QUESTION_ID', 'PAGE_VERSION')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection_questions',
            unique_together={('VERSION', 'ID')},
        ),
        migrations.AlterUniqueTogether(
            name='stakeholder_to_page',
            unique_together={('PAGE', 'PAGE_VERSION', 'STAKEHOLDER', 'STAKEHOLDER_VERSION')},
        ),
        migrations.CreateModel(
            name='QUESTIONS',
            fields=[
                ('QUESTION', models.AutoField(primary_key=True, serialize=False)),
                ('VERSION', models.IntegerField(default=1)),
                ('POINTS', models.IntegerField(default=1)),
                ('QUESTION_TEXT', models.TextField(default='default')),
                ('QUESTION_SUMMARY', models.TextField(default='default')),
            ],
            options={
                'unique_together': {('QUESTION', 'VERSION')},
            },
        ),
        migrations.RemoveField(
            model_name='action_page',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pages_to_scenario',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='pages_to_scenario',
            name='page_version',
        ),
        migrations.RemoveField(
            model_name='pages_to_scenario',
            name='scenario_id',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='page_version',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='reflection_question_id',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='reflection_question_version',
        ),
        migrations.RemoveField(
            model_name='reflection_questions',
            name='PAGE',
        ),
    ]
