# Generated by Django 2.2.12 on 2021-04-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210419_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='tables.STUDENTS', unique=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
