# Generated by Django 2.2.12 on 2021-04-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20210419_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='STAKEHOLDER',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coverage2', to='tables.STAKEHOLDERS', unique=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
