# Generated by Django 2.2.12 on 2021-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20210419_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='POINTS',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conversations',
            name='QUESTION_SUMMARY',
            field=models.TextField(default='default'),
        ),
    ]
