# Generated by Django 2.2.12 on 2021-04-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210422_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='POINTS',
        ),
        migrations.RemoveField(
            model_name='conversations',
            name='QUESTION_SUMMARY',
        ),
        migrations.AddField(
            model_name='pages',
            name='COMPLETED',
            field=models.BooleanField(default=False),
        ),
    ]
