# Generated by Django 2.2.12 on 2021-04-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210426_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='NEXT_PAGE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages2', to='tables.PAGES', unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='NEXT_PAGE_VERSION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages3', to='tables.PAGES', to_field='VERSION', unique=True),
        ),
    ]
