# Generated by Django 2.2.12 on 2021-04-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20210429_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='STAKEHOLDER',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coverage2', to='tables.STAKEHOLDERS', unique=True),
        ),
    ]
