# Generated by Django 3.1.7 on 2021-05-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20210429_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='STAKEHOLDER_VERSION',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='STAKEHOLDER_VERSION',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='NEXT_PAGE',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='NEXT_PAGE_VERSION',
        ),
        migrations.RemoveField(
            model_name='reflections_taken',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='PAGE_VERSION',
        ),
        migrations.AddField(
            model_name='action_page',
            name='ACTION_PAGE_ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action_page',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='STUDENTS',
            field=models.ManyToManyField(related_name='COURSES', through='tables.STUDENTS_TO_COURSE', to='tables.STUDENTS'),
        ),
        migrations.AddField(
            model_name='courses',
            name='professors',
            field=models.ManyToManyField(related_name='COURSES', through='tables.PROFESSORS_TO_COURSES', to='tables.PROFESSORS'),
        ),
        migrations.AddField(
            model_name='courses',
            name='scenarios',
            field=models.ManyToManyField(related_name='COURSES', through='tables.SCENARIOS_FOR', to='tables.SCENARIOS'),
        ),
        migrations.AddField(
            model_name='courses_to_scenario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generic_page',
            name='GENERIC_PAGE_ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='NEXT_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages2', to='tables.pages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages_to_scenario',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professors_to_courses',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_question_to_page',
            name='PAGE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tables.pages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_questions',
            name='REFLECTION_QUESTION_ID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection_questions',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenarios_for',
            name='SCENARIO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tables.scenarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenarios_for',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholders',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_to_course',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action_page',
            name='CHOICE',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='action_page',
            name='PAGE',
            field=models.ForeignKey(db_column='page', on_delete=django.db.models.deletion.CASCADE, to='tables.pages'),
        ),
        migrations.AlterField(
            model_name='action_page',
            name='RESULT_PAGE',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action_page',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='CONVERSATION',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='QUESTION',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='RESPONSE',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='STAKEHOLDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations1', to='tables.stakeholders', to_field='STAKEHOLDER'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='COURSE',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='NAME',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses_to_scenario',
            name='COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.courses'),
        ),
        migrations.AlterField(
            model_name='courses_to_scenario',
            name='SCENARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.scenarios'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='COVERAGE_SCORE',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='ISSUE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage1', to='tables.issues'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='STAKEHOLDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage2', to='tables.stakeholders', to_field='STAKEHOLDER'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='GENDER',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='GRADE',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Freshmen'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior')], max_length=1),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='MAJOR',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='RACE',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='generic_page',
            name='BODY',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generic_page',
            name='PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_page1', to='tables.pages', to_field='PAGE'),
        ),
        migrations.AlterField(
            model_name='generic_page',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='BODY',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='PAGE',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='PAGE_TYPE',
            field=models.CharField(choices=[('I', 'INTRO'), ('F', 'FEEDBACK'), ('G', 'GENERIC'), ('R', 'REFLECTION'), ('S', 'STAKEHOLDER'), ('A', 'ACTION')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pages',
            name='VERSION',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pages_to_scenario',
            name='PAGE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_page1', to='tables.pages', to_field='PAGE'),
        ),
        migrations.AlterField(
            model_name='professors',
            name='FNAME',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professors',
            name='LNAME',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='PROFESSOR',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professors_to_courses',
            name='COURSE',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='tables.courses'),
        ),
        migrations.AlterField(
            model_name='professors_to_courses',
            name='PROFESSOR',
            field=models.ForeignKey(db_column='professor', on_delete=django.db.models.deletion.CASCADE, to='tables.professors'),
        ),
        migrations.AlterField(
            model_name='professors_to_scenario',
            name='PROFESSOR',
            field=models.ForeignKey(db_column='professor', on_delete=django.db.models.deletion.CASCADE, to='tables.professors'),
        ),
        migrations.AlterField(
            model_name='professors_to_scenario',
            name='SCENARIO',
            field=models.ForeignKey(db_column='scenario', on_delete=django.db.models.deletion.CASCADE, to='tables.scenarios'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='POINTS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='QUESTION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='QUESTION_SUMMARY',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='QUESTION_TEXT',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reflection_question_to_page',
            name='REFLECTION_QUESTION_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.reflection_questions'),
        ),
        migrations.AlterField(
            model_name='reflection_questions',
            name='REFLECTION_QUESTION',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reflection_questions',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='REFLECTIONS',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reflections_taken',
            name='RESPONSE_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.responses'),
        ),
        migrations.AlterField(
            model_name='response_to_action_page',
            name='ACTION_PAGE',
            field=models.ForeignKey(db_column='action_page', on_delete=django.db.models.deletion.CASCADE, to='tables.action_page'),
        ),
        migrations.AlterField(
            model_name='response_to_action_page',
            name='RESPONSE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.responses'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='COURSE',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='tables.courses'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='PAGE',
            field=models.ForeignKey(db_column='page', on_delete=django.db.models.deletion.CASCADE, to='tables.pages'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='RESPONSE_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responses',
            name='SCENARIO',
            field=models.ForeignKey(db_column='scenario', on_delete=django.db.models.deletion.CASCADE, to='tables.scenarios'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='STUDENT',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to='tables.students'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='CONVERSATION',
            field=models.ForeignKey(db_column='conversation', on_delete=django.db.models.deletion.CASCADE, to='tables.conversations'),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='RESPONSE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.responses'),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='SCORE',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='STAKEHOLDER',
            field=models.ForeignKey(db_column='stakeholder', on_delete=django.db.models.deletion.CASCADE, to='tables.stakeholders'),
        ),
        migrations.AlterField(
            model_name='responses_to_conversations',
            name='STAKEHOLDER_VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='NAME',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='SCENARIO',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='VERSION',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scenarios_for',
            name='COURSE',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='tables.courses'),
        ),
        migrations.AlterField(
            model_name='scenarios_for',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stakeholder_to_page',
            name='PAGE',
            field=models.ForeignKey(db_column='page', on_delete=django.db.models.deletion.CASCADE, to='tables.pages'),
        ),
        migrations.AlterField(
            model_name='stakeholder_to_page',
            name='STAKEHOLDER',
            field=models.ForeignKey(db_column='stakeholder', on_delete=django.db.models.deletion.CASCADE, to='tables.stakeholders'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='DESCRIPTION',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='ENABLE_MULTI_CONVO',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='INTRODUCTION',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='JOB',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='NAME',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='SCENARIO',
            field=models.ForeignKey(db_column='scenario', on_delete=django.db.models.deletion.CASCADE, to='tables.scenarios'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='STAKEHOLDER',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='VERSION',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='COURSE',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='tables.courses'),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='DATE_TAKEN',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='END_TIME',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='SCENARIO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.scenarios'),
        ),
        migrations.AlterField(
            model_name='student_times',
            name='START_TIME',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_times',
            name='STUDENT',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to='tables.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='FNAME',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='LNAME',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='STUDENT',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students_to_course',
            name='COURSE',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='tables.courses'),
        ),
        migrations.AlterField(
            model_name='students_to_course',
            name='STUDENT',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, to='tables.students'),
        ),
        migrations.AlterUniqueTogether(
            name='action_page',
            unique_together={('ACTION_PAGE_ID', 'VERSION')},
        ),
        migrations.AlterUniqueTogether(
            name='generic_page',
            unique_together={('GENERIC_PAGE_ID', 'VERSION')},
        ),
        migrations.AlterUniqueTogether(
            name='pages_to_scenario',
            unique_together={('PAGE_ID', 'SCENARIO_ID')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection_question_to_page',
            unique_together={('REFLECTION_QUESTION_ID', 'PAGE')},
        ),
        migrations.AlterUniqueTogether(
            name='reflection_questions',
            unique_together={('REFLECTION_QUESTION_ID', 'VERSION')},
        ),
        migrations.AlterUniqueTogether(
            name='response_to_action_page',
            unique_together={('RESPONSE_ID', 'ACTION_PAGE')},
        ),
        migrations.AlterUniqueTogether(
            name='scenarios_for',
            unique_together={('SCENARIO', 'COURSE')},
        ),
        migrations.AlterUniqueTogether(
            name='stakeholder_to_page',
            unique_together={('PAGE', 'STAKEHOLDER')},
        ),
        migrations.AlterUniqueTogether(
            name='student_times',
            unique_together={('STUDENT', 'COURSE', 'SCENARIO_ID')},
        ),
        migrations.RemoveField(
            model_name='action_page',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='pages_to_scenario',
            name='PAGE_VERSION',
        ),
        migrations.RemoveField(
            model_name='pages_to_scenario',
            name='SCENARIO_VERSION',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='PAGE_ID',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='PAGE_VERSION',
        ),
        migrations.RemoveField(
            model_name='reflection_question_to_page',
            name='REFLECTION_QUESTION_VERSION',
        ),
        migrations.RemoveField(
            model_name='reflection_questions',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='response_to_action_page',
            name='ACTION_PAGE_VERSION',
        ),
        migrations.RemoveField(
            model_name='scenarios_for',
            name='SCENARIO_ID',
        ),
        migrations.RemoveField(
            model_name='stakeholder_to_page',
            name='PAGE_VERSION',
        ),
        migrations.RemoveField(
            model_name='stakeholder_to_page',
            name='STAKEHOLDER_VERSION',
        ),
        migrations.CreateModel(
            name='STAKEHOLDERS_TO_QUESTIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION', models.ForeignKey(db_column='question', on_delete=django.db.models.deletion.CASCADE, to='tables.questions')),
                ('STAKEHOLDER', models.ForeignKey(db_column='stakeholder', on_delete=django.db.models.deletion.CASCADE, to='tables.stakeholders')),
            ],
            options={
                'unique_together': {('STAKEHOLDER', 'QUESTION')},
            },
        ),
    ]
