# Generated by Django 3.1.7 on 2021-05-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20210504_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic_page',
            name='ID',
        ),
        migrations.AddField(
            model_name='generic_page',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action_page',
            name='PAGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_page1', to='tables.pages'),
        ),
    ]
