# Generated by Django 3.1.7 on 2021-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20210504_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_page',
            name='id',
        ),
        migrations.AddField(
            model_name='action_page',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
