# Generated by Django 3.1.7 on 2021-03-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210311_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(related_name='course', through='api.PartOf', to='api.Scenario'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='of_class', to='api.webuser'),
            preserve_default=False,
        ),
    ]
