# Generated by Django 3.1.7 on 2021-03-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210311_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fullName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(related_name='course', through='api.PartOf', to='api.Scenario'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webuser'),
        ),
    ]
