# Generated by Django 3.1.7 on 2021-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210311_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fullName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(related_name='course', through='api.PartOf', to='api.Scenario'),
        ),
    ]
