# Generated by Django 3.1.7 on 2021-03-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210311_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(related_name='course', through='api.PartOf', to='api.Scenario'),
        ),
        migrations.AlterField(
            model_name='partof',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='partof',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario'),
        ),
    ]
