# Generated by Django 3.1.7 on 2021-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210311_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(related_name='course', through='api.PartOf', to='api.Scenario'),
        ),
    ]
