# Generated by Django 3.1.7 on 2021-03-11 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210311_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='demographics', serialize=False, to='api.webuser')),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('OT', 'OTHER')], max_length=2)),
                ('race', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'DEMOGRAPHICS',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(related_name='course', through='api.PartOf', to='api.Scenario'),
        ),
        migrations.AlterModelTable(
            name='partof',
            table='PARTOF',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('choice', models.CharField(max_length=300)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'RESPONSES',
                'ordering': ['scenario'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('importance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenario')),
            ],
            options={
                'db_table': 'ISSUES',
                'ordering': ['scenario'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('response', models.TextField(max_length=100)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.webuser')),
            ],
            options={
                'db_table': 'CONVERSATIONS',
            },
        ),
    ]
