# This workflow will do a clean install of node dependencies, build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: false
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Editor
        working-directory: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
        run: yarn install && yarn run build
      - name: Build Simulator
        working-directory: ./simulator/frontend/
        run: yarn install && yarn run build
      - name: Bundling artifact
        run: |
          mkdir ethisim;
          cp -r ./apache ./ethisim/;
          mkdir ./ethisim/apache/build;
          cp -r ./Ghost_in_the_Shell/client_folder_react_app/ethisim/build ./ethisim/apache/build/se;
          cp -r ./simulator/frontend/build ./ethisim/apache/build/simulator;
          cp -r ./moral_kombat_backend ./ethisim/;
          cp -r ./segfault ./ethisim/;
      - name: Stopping current docker
        run: docker-compose -f /ethisim/docker-compose-deploy.yml down
      - name: Remove exisitng apache files
        run: |
          if [ -e /ethisim/apache/ ]; then echo "removing /ethisim/apache/*"; rm -rf /ethisim/apache/*; fi
      - name: Copy artifact to server
        run: |
          if [ -e /ethisim/ ]; then echo "copying to /ethisim"; cp -r ./ethisim/* /ethisim/; fi
      - name: Starting new server
        run: docker-compose -f /ethisim/docker-compose-deploy.yaml up --build -d --remove-orphans
