name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Editor
        working-directory: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
        run: yarn install && PUBLIC_URL=/se yarn run build
      - name: Upload Editor artifact
        uses: actions/upload-artifact@v2
        with:
          name: editor-frontend
          path: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/build/
      - name: Build Simulator
        working-directory: ./simulator/frontend/
        run: yarn install && PUBLIC_URL=/simulator yarn run build
      - name: Upload Simulator artifact
        uses: actions/upload-artifact@v2
        with:
          name: sim-frontend
          path: ./simulator/frontend/build/

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - name: Downloading artifacts
        uses: actions/download-artifact@v2  
      - name: Bundling server
        run: |
          mkdir ethisim;
          mkdir ./ethisim/ssl
          mkdir ./ethisim/ssl/certs
          mkdir ./ethisim/ssl/private
          mkdir ./ethisim/shib_config
          cp -r ./apache ./ethisim/;
          cp -r ./env-template ./ethisim/;
          cp ./start.sh ./ethisim/;
          cp docker-compose-deploy.yaml ./ethisim/docker-compose.yaml;
          cp requirements.txt ./ethisim/requirements.txt;
          cp Dockerfile ./ethisim/Dockerfile;
          mkdir ./ethisim/apache/build ./ethisim/apache/build/se ./ethisim/apache/build/simulator;
          cp -r ./editor-frontend/* ./ethisim/apache/build/se;
          cp -r ./sim-frontend/* ./ethisim/apache/build/simulator;
          cp ./apache/.htaccess ./ethisim/apache/build/se;
          cp ./apache/.htaccess ./ethisim/apache/build/simulator;
          if [ -e ./moral_kombat_backend ]; then cp -r ./moral_kombat_backend ./ethisim/; fi;
          if [ -e ./segfault ]; then cp -r ./segfault ./ethisim/; fi; 
          zip -r ethisim.zip ./ethisim/;
          cp ethisim.zip ./ethisim/;
      - name: Upload zip as release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ethisim.zip