name: test-app

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Editor
        working-directory: ./Ghost_in_the_Shell/client_folder_react_app/ethisim/
        run: yarn install && yarn run build
      - name: Build Simulator
        working-directory: ./simulator/frontend/
        run: yarn install && yarn run build
